import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header style={{ backgroundColor: "#f0f", textAlign: "center", padding: "20px" }}>
        <h3 className="text-2xl font-bold text-slate-100">Header</h3>
      </header>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <footer style={{ backgroundColor: "#333", textAlign: "center", padding: "20px", position: "fixed", width: "100%", bottom: 0 }}>
        <p className="text-slate-100">Copyright © 2025</p>
      </footer>
    </html>
  );
}
